name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: ./.github/workflows/go-setup

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu make

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Context for Buildx
        shell: bash
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
            -e DOCKER_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            goreleaser/goreleaser-cross:v1.22.2 release --clean

